[project]
name = "lab4"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pytest>=8.4.2",
    "logging>=0.4.9.6",
    "rich>=14.2.0"
]
